<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/admin.Master" AutoEventWireup="true" CodeBehind="Templates.aspx.cs" Inherits="GoLA2.Admin.Templates" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../Content/WebForms.css" rel="stylesheet" type="text/css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>All Templates</h2>
    <asp:HyperLink Text="Upload Template" NavigateUrl="UploadTemplate.aspx" CssClass="btn btn-default" runat="server" />
    <p></p>
    <asp:GridView ID="gridTemplates" runat="server" CssClass="table" 
                  GridLines="None" AutoGenerateColumns="False" 
                  AllowSorting="True" OnSorting="gridTemplates_SortChanging"
                  AllowPaging="True" PageSize="3" OnPageIndexChanging="gridTemplates_PageIndexChanging"
                  AutoGenerateDeleteButton="True" OnRowDeleting="gridTemplate_Deleting" datakeynames="UserTemplateID">
        <Columns>
            <asp:BoundField DataField="UserTemplateID" HeaderText="Template ID" SortExpression="UserTemplateID"/>
            <asp:BoundField DataField="UserID" HeaderText="User ID" SortExpression="UserID" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Height" HeaderText="Height" SortExpression="Height" />
            <asp:BoundField DataField="Width" HeaderText="Width" SortExpression="Width" />
            <asp:TemplateField HeaderText="Cells" SortExpression="Cells">
                <ItemTemplate>
                    <pre><%# Eval("Cells") %></pre>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <PagerStyle CssClass="pagination-ys" />
    </asp:GridView>
</asp:Content>

