<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/admin.Master" AutoEventWireup="true" CodeBehind="Users.aspx.cs" Inherits="GoLA2.Admin.Users" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../Content/WebForms.css" rel="stylesheet" type="text/css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>All Users</h2>
    <asp:GridView ID="gridUsers" runat="server" CssClass="table" 
                  GridLines="None" AutoGenerateColumns="False"
                  AllowSorting="True" OnSorting="gridUsers_SortChanging"
                  AllowPaging="True" PageSize="3" OnPageIndexChanging="gridUsers_PageIndexChanging" 
                  AutoGenerateDeleteButton="True" OnRowDeleting="gridUser_Deleting" datakeynames="UserID">
        <Columns>
            <asp:BoundField DataField="UserID" HeaderText="User ID" SortExpression="UserID" />
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            <asp:BoundField DataField="FirstName" HeaderText="First Name" SortExpression="FirstName" />
            <asp:BoundField DataField="LastName" HeaderText="Last Name" SortExpression="LastName" />
            <asp:BoundField DataField="IsAdmin" HeaderText="Admin" SortExpression="IsAdmin" />
        </Columns>
        <PagerStyle CssClass="pagination-ys" />
    </asp:GridView>
    <asp:Label ID="debug" runat="server"></asp:Label>
</asp:Content>
